name: BukkitPixelmonPlaceholders
version: 1.0.8
author: EverNife
main: br.com.finalcraft.bukkitpixelmonplaceholders.BukkitPixelmonPlaceholders
depend: [ EverNifeCore ]
softdepend: [ PlaceholderAPI ]
api-version: 1.13